apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: prediction
  labels:
    app: prediction
description: delivery pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles:
    - staging
  # - targetId: prod
  #   profiles:
  #   - prod