apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: Target for staging environment
gke:
  cluster: projects/virtual-anomaly/locations/us-central1-b/clusters/training-cluster-beta